### ISSUE TITLE
Unmarshal to single struct

### ISSUE THREAD

**Issue by pengux** [manyminds/api2go#113]
Currently jsonapi doesn't seem to allow unmarshalling to a single struct instead of a []UnmarshalIdentifier, but according to the spec:

> The request MUST include a single resource object as primary data

**Comment by wwwdata** [comment]
you are right, this is confusing. We should add the possibility to use a single struct as well.

**Comment by wwwdata** [comment]
we had a slice for it because in a previous specification it was possible to create multiple objects. I will open a PR soon that allows to use a struct directly. I would like to support both because of this idea here #112. From a client perspective (if we will implement that too) it is still required to unmarshal multiple objects.

**Comment by pengux** [comment]
Yes, I agree with supporting both. The standard can be a single object and then we can have a for example UnmarshalManyToJSON() for multiple objects.
