### ISSUE TITLE
More accurate error responses

### ISSUE THREAD

**Issue by stephenmuss** [manyminds/api2go#115]
It doesn't make sense to always return an error response with a 500 status code.

For example if a client sends a request to retrieve a post at `/v1/posts/a` where `a` should be an integer id it would make sense to be able to return a 400 client error response.

Likewise, if the client were to request `/v1/posts/1` where no post with the id `1` exists it should be possible to return a 404 not found response.

It would be great to have some kind of control over the error responses and status codes.

Maybe it could be possible for a source to implement an interface which has some level of control over how to render an error response or perhaps return some kind of custom Error struct.

**Comment by wwwdata** [comment]
Hi, yes we have a custom error which includes a http status code. You can do it like here in the example

https://github.com/manyminds/api2go/blob/master/examples/crud_example.go#L317

```go
func NewHTTPError(err error, msg string, status int) HTTPError 
```

err is an optional go error that you can put in, for example if your underlying database had an error. Otherwise just use `nil`, an error message, and a http statuscode like

```go
return api2go.NewHTTPError(nil, "not found", http.StatusNotFound)
```

It seems we completely forgot to also include this into our Readme. I will add that later. Did that answer your question?

**Comment by stephenmuss** [comment]
That's perfect. I should have looked into the example as well. Thanks!
