### ISSUE TITLE
Handle update with payload changes

### ISSUE THREAD

**Issue by geoffgarside** [manyminds/api2go#138]
The specification says that if you're changing any of the properties during the update process, such as computing a sha or setting an `updated-at` timestamp that you need to respond with a 200 OK and return the resource information to the client. At the moment the `handleUpdate` function is only able to respond with a `204 No Content` response.

Is it possible to match this requirement with the current API?

**Comment by sharpner** [comment]
It should be possible, but it isn't. Thanks for reporting this issue!

**Comment by wwwdata** [comment]
Just a quick copy&paste of the return status codes:

> 202 Accepted

> If an update request has been accepted for processing, but the processing has not been completed by the time the server responds, the server MUST return a 202 Accepted status code.

> 200 OK

>If a server accepts an update but also changes the resource(s) in ways other than those specified by the request (for example, updating the updated-at attribute or a computed sha), it MUST return a 200 OK response. The response document MUST include a representation of the updated resource(s) as if a GET request was made to the request URL.

>A server MUST return a 200 OK status code if an update is successful, the client's current attributes remain up to date, and the server responds only with top-level meta data. In this case the server MUST NOT include a representation of the updated resource(s).

>204 No Content

>If an update is successful and the server doesn't update any attributes besides those provided, the server MUST return either a 200 OK status code and response document (as described above) or a 204 No Content status code with no response document.

>403 Forbidden

>A server MUST return 403 Forbidden in response to an unsupported request to update a resource or relationship.

>404 Not Found

>A server MUST return 404 Not Found when processing a request to modify a resource that does not exist.

>A server MUST return 404 Not Found when processing a request that references a related resource that does not exist.

>409 Conflict

>A server MAY return 409 Conflict when processing a PATCH request to update a resource if that update would violate other server-enforced constraints (such as a uniqueness constraint on a property other than id).

>A server MUST return 409 Conflict when processing a PATCH request in which the resource object's type and id do not match the server's endpoint.

>A server SHOULD include error details and provide enough information to recognize the source of the conflict.

>Other Responses

>A server MAY respond with other HTTP status codes.

>A server MAY include error details with error responses.

>A server MUST prepare responses, and a client MUST interpret responses, in accordance with HTTP semantics.

original here: http://jsonapi.org/format/#crud-updating-responses

**Comment by wwwdata** [comment]
we also need the possibility to  return different status codes for create and delete methods.

So
- Create
- Update
- Delete

Methods need the possibility to return a different status code. And when the update method returns with status 200, because it updated a timestamp server-side it also needs to respond with the updated resource. 
Currently, the update method always returns nothing and the 204 No Content status. We have to check the other status code and fetch the updated resource via FindOne so we can return it.

I will summarize the status codes and it's meanings:

## Create
### 201 Created
`POST` did not include a Client-Generated ID. The resource has been created successfully and needs to b e returned with a `self` and `links` member and `Location` header. This is the status quo.
### 202 Accepted
Creation was accepted, but processing did not complete. In that case, return 202 and of course no created resource, because its not there yet.
### 204 No Content
The resource did include a Client-Generated ID. Do not send a response document, because nothing was added server-side. 
### 403 Forbidden
Unsupported request.We should return an error object here. Normally I would do a security layer which checks for a session/token before the json-api routes and then returns 403. But I suggest to take our custom error object here with a 403 code.
### 409 Conflict
- A Client-Generated ID already exists.
- The type key is wrong (this should be handled before resource action in our api layer)
- Return error object here with details

## Update
I do not distinguish between Records and Relationships here. Currently relationship updates go into the normal Update method too. Should be fine I guess. Relationship updates do only specify the codes: 202, 204, 200 and 403 and the meaning is the same as with Record Updates.

### 202 Accepted
Update was accepted, but processing is not done, only return 202 Code and no resource.
### 200 OK
If a server changes the resource like updating a timestamp. Return 200 and updated resource.
### 204 No Content
Status quo, update was successful, server did not change anything.
### 403 Forbidden
Standard forbidden case
### 404 Not Found
Is currently done via returning an error object with 404 Status code.
### 409 Conflict
Unique constraint or type and id mismatch. Needs our error object too.

## Delete
### 202 Accepted
Like the other ones, deletion has been triggered but not completed.
### 204 No Content
Successful deletion
### 200 OK
Deletion was successful, response with top-level meta data only. Hmm, yea, that's a tricky case here I guess.

**Comment by geoffgarside** [comment]
Regarding the 202 Accepted response code, from RFC2616

> The 202 response is intentionally non-committal. Its purpose is to allow a server to accept a request for some other process (perhaps a batch-oriented process that is only run once per day) without requiring that the user agent's connection to the server persist until the process is completed. The entity returned with this response SHOULD include an indication of the request's current status and either a pointer to a status monitor or some estimate of when the user can expect the request to be fulfilled.

I'm not sure how this plays into jsonapi as the specification doesn't make any mention of this. I don't therefore know if there would be some kind of data response that should be sent with a 202 response or if the server would have some Location or other suitable header that it would be able to send back to fulfil the RFC recommendation.
