### ISSUE TITLE
Manual marshal without included structs

### ISSUE THREAD

**Issue by dustinsmith1024** [manyminds/api2go#153]
I want to include the related structs on my single resource routes but not on the collection routes.  I can achieve this by adding a boolean attribute to my struct `IncludeRelated` and then check that in the `GetReferencedStructs` method.

However, it might be nice to have an extra param on the Marshal methods to say if you want them included or not.  Or different methods to call when you don't want them included.

I could probably work on a PR if you guys like the idea or have a better one.

**Comment by wwwdata** [comment]
It is also possible to only include specific relations and not all of them. So a simple parameter is not enough. We would need a mechanism and conventions for that.

We intentionally left it this way for the user of api2go to implement it how he likes it best. As you said you could add an attribute to your struct in order to determine whether a relation or many relations need to be included. I am doing this on my project where I am using api2go like this too. And if you ask me I think this is the best and most flexible way. But we are always open for suggestions.

**Comment by sharpner** [comment]
I don't think introducing a parameter is the right way to go, we are currently in the process of stabilizing the api for 1.0 and params for optional behaviour always break it again. 

If we decide to introduce such a feature into api2go we should use optional interfaces imho.

**Comment by dustinsmith1024** [comment]
Sounds good, Ill keep using the extra param for now.
