### ISSUE TITLE
Meta information

### ISSUE THREAD

**Issue by theduke** [manyminds/api2go#156]
I really need the ability to add meta information to the response.

One option would be to add an additional meta or response argument to all the interfaces,
or add an additional returned meta object.

This would require a lot of refactoring and breaks compatability.
Not ideal.

Another "dirtier" solution is to add a Meta [string]interface{} property to the Request struct,
so in all handling functions one could just add the meta information there.

Of course, putting response data in a request object is not very intuitive or clean, but does not break compatablity an is not as much work.

Would you accept a PR that does this?

**Comment by wwwdata** [comment]
hi, i am now back from vacation and will complete my work on #147 once this is merged, it is possible to add meta information to every response. Can you look at my PR and check if that would be a good solution for you? We are changing a lot with that and basically breaking the api because we introduce a new Response object.

**Comment by sharpner** [comment]
It got merged, have a look at: https://github.com/manyminds/api2go#responder for the usage.

**Comment by theduke** [comment]
Perfect, thanks.
