### ISSUE TITLE
Missing mandatory id key

### ISSUE THREAD

**Issue by trapias** [manyminds/api2go#159]
Hello,
I had to modify my model "masking" the ID not to let it be visible within object attributes, e.g. getting a list of users (/users): 

	type User struct {
		ID          string      `json:"-"`
		Name        string      `jsonapi:"name=name"`
		Password    string      `json:"-"`
		// ...
	}

If I don't set the son tag, the ID is shown even if I also get GetID and SetiD on the model, just like in the crud_example. This is not apparently affecting resource methods, except Update: I get errors if I don't put the id in the posted json.
That is, a PATCH call to update must be like:

	curl -vX PATCH https://localhost:8000/api/1/users/4c3c23c2-2e2f-5fc8-8911-558176b4f7d7 --header "Content-Type: application/vnd.api+json"  --header "Authorization: Bearer ..." -d '{ "data" : {"type" : "users", "id": "4c3c23c2-2e2f-5fc8-8911-558176b4f7d7",  "attributes": {"name" : "new name" }}}'

If I don't  put the id field in data I get error **403, missing mandatory id key**. Nothing changes if I remove the son tag on ID in my model.
Where can this come from?

I modified my UserStorage methods to have a couple of more parameters, like:

	func (s *UserStorage) Update(db *sql.DB, userid string, c model.User) error {

but I have the same params for all other methods, and all is working properly. Could it be this causing the problem?

A second problem is about the "masked" password field: it is always sent to the update method as an empty string, how could I avoid this?

**Comment by wwwdata** [comment]
I don't see a problem here, everything you described works as intended. You **must** put an id field inside `data`. And yes, you have to use the json ignore tag to exclude it from the `attributes` object. We don't know the name of your id field, that's why we implemented the `GetID()` and `SetID()` interface methods.

I cannot help you with your second problem. You either include a password in your resource as a normal field or not. This is very dependent on your application. Normally you never want to expose a pasword hash. So it would be advisable to use another  resource for logins/registrations that has a password field. But you have to decide by yourself how to do it.

**Comment by trapias** [comment]
@wwwdata Ah! I was misled by the example at  https://github.com/manyminds/api2go/blob/master/examples/crud_example.go, where the Update example in curl does not include the id in data:

	curl -vX PATCH http://localhost:31415/v0/users/1 -d '{ "data" : {"type" : "users", "attributes": {"user-name" : "better marvin", }}}'

So I thought the id was acquired from the url via httprouter params.

About the password I agree I have to solve myself in another way. 
Thank you, once more :smile:

**Comment by wwwdata** [comment]
ok, that is a mistake then in the example comment. I will fix that
