### ISSUE TITLE
Remove relationships attribute when no relationships are included?

### ISSUE THREAD

**Issue by faeronsayn** [manyminds/api2go#211]
I'm including relationships currently and marshalling them with the `jsonapi` plugin. 

I have a Group struct and a User struct with a many-to-many relation.

When I return a list of groups, I get their respective users and include them. After I marshal them though Groups have the `relationships` attribute with everything done properly. 

In the included attribute the user resource objects exist, the issue is that the `relationships` in the user resource object has an `empty groups` relationship, which isn't correct.

I'm wondering if there is a way to either remove the `relationships` attribute entirely for included relationships or somehow parse it properly.

**Comment by wwwdata** [comment]
Ok, so to be correct the `User` object needs the to-one relationship to the group it belongs to right? This should be working if you correctly implemented the `GetReferencedIDs() []ReferenceID` IDs relationship on your `User` struct.

Leaving the relationship object out of the json is not possible, because that violates the jsonapi spec and would be lying about your data structure. However it is possible to not load anything to just show a client that there is a relationship, but we don't know the state of it. To do that, you can omit the `data` field from the relationship in the json. Api2go supports this: see: https://godoc.org/github.com/manyminds/api2go/jsonapi#Reference
You have to set the `IsNotLoaded` flag to true when you return the description of the relationship in the `GetReferences() []Reference` method of your `User` struct. 

Their spec says this: http://jsonapi.org/format/#document-top-level
> A "relationship object" MUST contain at least one of the following:

> - links: a links object containing at least one of the following:
>   - self: a link for the relationship itself (a "relationship link"). This link allows the client to directly manipulate the relationship. For example, it would allow a client to remove an author from an article without deleting the people resource itself.
>   - related: a related resource link
> - data: resource linkage
> - meta: a meta object that contains non-standard meta-information about the relationship.

Are you sure that you implemented everything correctly? Because we have tests for that: https://github.com/manyminds/api2go/blob/master/jsonapi/marshal_test.go#L158

**Comment by faeronsayn** [comment]
> Ok, so to be correct the User object needs the to-one relationship to the group it belongs to right? This should be working if you correctly implemented the GetReferencedIDs() []ReferenceID IDs relationship on your User struct.

It's a many-to-many relationship between users and groups. Users belong to multiple groups and a group can belong to multiple users. 

Here is some code of how i've implemented those methods (I've basically followed the example) 

```
// group.go

// GetReferencedStructs to satisfy the jsonapi.MarhsalIncludedRelations interface
func (g Group) GetReferencedStructs() []jsonapi.MarshalIdentifier {
	result := []jsonapi.MarshalIdentifier{}
	for key := range g.Users {
		result = append(result, g.Users[key])
	}

	return result
}

func (g Group) GetReferencedIDs() []jsonapi.ReferenceID {
	result := []jsonapi.ReferenceID{}
	for _, user := range g.Users {
		result = append(result, jsonapi.ReferenceID{
			ID:   user.GetID(),
			Type: "users",
			Name: "users",
		})
	}
	return result
}
```


and for the User
```
// user.go

// GetReferencedIDs satisfies the jsonapi.MarshalLinkedRelations interface
func (u User) GetReferencedIDs() []jsonapi.ReferenceID {
	result := []jsonapi.ReferenceID{}
	for _, group := range u.Groups {
		result = append(result, jsonapi.ReferenceID{
			ID:   group.GetID(),
			Type: "groups",
			Name: "groups",
		})
	}
	return result
}

// GetReferencedStructs to satisfy the jsonapi.MarhsalIncludedRelations interface
func (u User) GetReferencedStructs() []jsonapi.MarshalIdentifier {
	result := []jsonapi.MarshalIdentifier{}
	for key := range u.Groups {
		result = append(result, u.Groups[key])
	}
	return result
}
```

**Comment by wwwdata** [comment]
Are you sure that all the IDs or referenced structs are set before you marshal? I would guess that the problem is that the groups reference IDs are not set before you marshal the Users. If they are set. This is a bug and we need a test to confirm it. 

In your case you would have to set the group references into the user struct and the user references in the group struct right? Because they are linked together in both directions.

**Comment by faeronsayn** [comment]
Correct, that's not a simple task, without doing a weird or manipulating the data once it comes back. 

But in any case, there is always the case of not displaying inverse relationships. Users don't have to have  have a relationship to the groups even though our backend knows that a relationship like this exists, the first end doesn't need to. 

Furthermore, in the case of not actually including the relationship in the response for some instances because we don't want to send a ton of stuff down in the same response, we can exclude the data field in the relationship. The only issue is the way that it is currently handled, you can display that the relationship `isNotLoaded` in a global manner. How can we do this per response? Some responses I might want to show the loaded relations, and in other cases, i might not.

**Comment by wwwdata** [comment]
What you are saying makes totally sense. It is a bit overkill to display the n-m relationship again. Api2go gives you the flexibility to display relationships how you like. That is why we have a method `GetReferences() []Reference` for it. This is not a global or static way, because it is a method that get's called everytime your structs are marshalled. So it's up to you to implement a mechanism that either sets the `isNotLoaded` flag or completely omits the relationship in these circumstances. 

An easy way to do it would be to add another field to the related n-m struct, so for example your user structs when you set them as a reference to a group, which indicates, that the `GetReferences() []Reference` has to omit the relationship to the group. It's really up to you how you do this. We intentionally choose this more un-restrictive way with the interfaces because of all the different database drivers/orms etc. that are out there and all behave differently.

**Comment by faeronsayn** [comment]
Hmm alright, makes sense.
