### ISSUE TITLE
How to opt in/out of sideloading relationships?

### ISSUE THREAD

**Issue by timrourke** [manyminds/api2go#246]
I'm looking for a way to implement jsonapi's `include` query param, as described [in the jsonapi spec.](http://jsonapi.org/format/#fetching-includes) My goal is to include a related entity's IDs by default, and opt into including the entire struct in the json payload by using the `include` query param. 

I saw [the IsNotLoaded flag](https://github.com/manyminds/api2go/blob/master/jsonapi/marshal.go#L35) referenced in `marshal.go`, but changing the state of that flag doesn't seem to effect whether or not the relationship is included.

What am I overlooking? In my model definition, implementing the interface as seen below doesn't seem to have any impact on the returned json.

```
func (m MyModel) GetReferences() []jsonapi.Reference {
	return []jsonapi.Reference{
		{
			Type: "coolRelationship",
			Name: "coolRelationship",
			IsNotLoaded: true,
		},
	}
}
```

Thanks for putting your work into this package, it's incredibly useful, and has made it a snap for me to get introduced to Go while making something meaningful.

**Comment by wwwdata** [comment]
`IsNotLoaded` only indicates, that you want to omit the `data` part. Because if you are sending an empty `data` object, it means that there are NO relationships. So if you skip it, it means: It's uncertain if there is related data, the client must find out with another Request. 

In order to include Reference-IDs you should just return them with the `GetReferencedIDs` method in your resource model struct. It's up to you to implement all this behaviour by yourself, especially when you need to set `IsNotLoaded` if you really want to skip references completely.

So what you need to do is just always let `GetReferencedIDs` return the reference IDs and it should work. 

If you look at the code here: https://github.com/manyminds/api2go/blob/0f0aba686fffe91897ee4b7e1d682efbfcbac7fd/jsonapi/marshal.go#L195
you see, that it's always called when api2go marshals.

**Comment by timrourke** [comment]
@wwwdata thanks so much for the speedy clarification. That clears things up quite a bit! 

I see that by simply implementing the `GetReferencedStructs` interface in my model, the relationships are automatically sideloaded. Do you have any recommendations about allowing the API consumer to opt into sideloading those relationships in a single request? Again, I feel like I'm overlooking something obvious here. I can't find the caller for the `MarshalIncludedRelations` interface.

For example, this route should include the relationships in the json response:

`mycoolapi.com/api/teachers?include=students.grades`

Whereas this would only include IDs:

`mycoolapi.com/api/teachers`

**Comment by timrourke** [comment]
Ah, I see it here: [https://github.com/manyminds/api2go/blob/0f0aba686fffe91897ee4b7e1d682efbfcbac7fd/jsonapi/marshal.go#L127](https://github.com/manyminds/api2go/blob/0f0aba686fffe91897ee4b7e1d682efbfcbac7fd/jsonapi/marshal.go#L127)

So it seems that if I want to explicitly opt into this behavior, I'll need to handle the `GetReferencedStructs` operation manually?

**Comment by wwwdata** [comment]
yes, you would have to check for the query  parameters and if present, implement some behavior that your `GetReferencedStructs` method returns the embedded structs.

**Comment by timrourke** [comment]
Thanks!
