### ISSUE TITLE
Mandatory JSON fields

### ISSUE THREAD

**Issue by TylerPachal** [manyminds/api2go#255]
I have a few models that have `not null` sql columns:

```
type Account struct {
	Email            *string `sql:"unique; not null";json:"email"`
	FirstName        *string `sql:"not null";json:"first_name"`
	LastName         *string `sql:"not null";json:"last_name"`
	Password         *string `sql:"not null";json:"password"`
	IsAdmin          *bool   `sql:"default:false";json:"is_admin"`
} 
```

Right now if someone passes in a JSON object which is missing one of these fields, the error will be handled by the database.  However I would like to handle the missing fields at the model unmarshalling level.  Is this possible?

**Comment by wwwdata** [comment]
Hi,

with the build in Unmarshaller of Go, this is not possible, because it does not support validations like your sql driver.

What you need is some sort of custom validation for your struct. If you directly want to validate it during Unmarshaling, it can be achieved by implementing the `Unmarshaler` [interface](https://godoc.org/encoding/json#Unmarshaler). You could add specific logic for validation that maybe also reads validation rules from Struct-Tags. But I cannot help you with this approach, it's just an idea and I haven't done it in this way myself.

Instead, I would recommend to use something like [govalidator](https://github.com/asaskevich/govalidator), because you will need a full validation system at some point anyways. Govalidator provides you with a huge set of validators that are ready to use and is customizable, so you can add your own validators as well. But this is an additional step, after the JSON document was already Unmarshalled into a struct.

**Comment by TylerPachal** [comment]
I ended up implementing the Unmarshaler interface.  Thanks.
