### ISSUE TITLE
Access to the current http.ResponseWriter object

### ISSUE THREAD

**Issue by Azuka** [manyminds/api2go#287]
I'm using Newrelic for monitoring, and the instrumentation [wraps the responseWriter as a transaction](https://docs.newrelic.com/docs/agents/go-agent/get-started/instrument-go-transactions#http-handler-txns). Would it be possible to expose the ResponseWriter object e.g. as part of `api2go.Request`?

I need access to the current transaction downstream, e.g. for monitoring database queries. Would this be possible, or is there another method I'm not aware of?

As an example, the router I use (based on gorilla mux) looks like this:

```go
func (h *hybridHandler) Handle(protocol, route string, handler routing.HandlerFunc) {
...
    h.router.Handle(newrelic.WrapHandle(h.nr, modroute, neg)).Methods(protocol)
}
```

**Comment by sharpner** [comment]
Quick suggestion before looking further into it, you could wrap the whole api2go handler before registering it (untested code):

```
api := api2go.NewAPI("v1")
http.ListenAndServe(":8080", newrelic.WrapHandleFunc(api.Handler()))
```
Does this help?

**Comment by wwwdata** [comment]
@sharpner yes that would work to set up the wrapping. But in order to log errors with newrelic they are extending the `ResponseWriter`. It comes down to this example from their docs

```go
func myHandler(w http.ResponseWriter, r *http.Request) {
    if txn, ok := w.(newrelic.Transaction); ok {
        txn.NoticeError(errors.New("my error message"))
    }
}
```

And in our api2go crud methods we don't have the `ResponseWriter` at the moment because we want a `Responder` object as return value which then get's marshalled and so on ... 

It would be possible to access the `ResponseWriter` in a middleware. But I guess this is not helping because the use case is that when something goes wrong inside a CRUD Resource, the error should be logged to newrelic, right?

**Comment by wwwdata** [comment]
@Azuka  But we are using our own `Request` object with more stuff in it. see:

```go
package api2go

import "net/http"

// Request contains additional information for FindOne and Find Requests
type Request struct {
	PlainRequest *http.Request
	QueryParams  map[string][]string
	Pagination   map[string]string
	Header       http.Header
	Context      APIContexter
}
```

So if you write a middleware that just sets the `ResponseWriter` into the middleware context of the `api2go.Request` it should be possible to get it inside the CRUD actions by accessing the `Context` object from the `Request` like this:

```go
func (s UserResource) FindAll(r api2go.Request) (api2go.Responder, error) {
	if r, ok := http.ResponseWriter(r.Context.Get('responseWriter')); ok {
		...
	}
```

Your middleware just has to write the `ResponseWriter` into the Context, that's it. Could you please test if this approach works?

**Comment by Azuka** [comment]
@wwwdata thanks. I'll try this in a couple hours and get back to you.

**Comment by Azuka** [comment]
Closing because this resolved my issue. I got to get back. Thanks @wwwdata

**Comment by josegonzalez** [comment]
Just checking in, does that responseWrite hack still work? The `net/http` doesn't appear to have a `ResponseWriter` method, and the `responseWriter` property doesn't appear to be populated in the context anymore. I'd love to have a way to set a header in my certain requests to handle cases like [Asynchronous Processing](https://jsonapi.org/recommendations/#asynchronous-processing).

**Comment by josegonzalez** [comment]
Okay after a little bit of sleep and re-reading of the above comments, turns out I forgot to write the `ResponseWriter` to my context. Here is the code to do that (I added it after I declared my resources):


```go
ResponsWriterMiddleware := func(c api2go.APIContexter, w http.ResponseWriter, r *http.Request) {
	c.Set("responseWriter", w)
}
api.UseMiddleware(ResponsWriterMiddleware)
```

Next, I wrote the header in my `AppResource::FindOne()` function. Note that `Context.Get()` returns two values, so the example code in the above comment doesn't quite work, but it's close. Here is what I used to set a header:

```go
if responseWriter, ok := r.Context.Get("responseWriter"); ok {
	w := responseWriter.(http.ResponseWriter)
	w.Header().Add("Content-Location", "https://example.com/photos/queue-jobs/5234")
}
```

Hope that helps someone in need :)
