### ISSUE TITLE
How to add multiple API versions

### ISSUE THREAD

**Issue by imhuytq** [manyminds/api2go#290]
What solution can I add more than one version of the API? Examples v1, v1.2, v2 ...

**Comment by sharpner** [comment]
Okay, this does not 100% work as intended, but you can mux it with a custom handler:

```
package main
import (
        "fmt"
        "log"
        "net/http"
        "strings"
        "github.com/manyminds/api2go"
        "github.com/manyminds/api2go/examples/model"
        "github.com/manyminds/api2go/examples/resource"
        "github.com/manyminds/api2go/examples/storage"
)
func main() {
        v1 := api2go.NewAPI("v1")
        v2 := api2go.NewAPI("v2")
        userStorage := storage.NewUserStorage()
        chocStorage := storage.NewChocolateStorage()
        v1.AddResource(model.User{}, resource.UserResource{ChocStorage: chocStorage, UserStorage: userStorage})
        v2.AddResource(model.User{}, resource.UserResource{ChocStorage: chocStorage, UserStorage: userStorage})
        handler := http.DefaultServeMux
        handler.HandleFunc("/", func(rw http.ResponseWriter, r *http.Request) {
                log.Printf("%s %b\n", r.RequestURI, strings.HasPrefix("/v1", r.RequestURI))
                if strings.HasPrefix(r.RequestURI, "/v1") {
                        v1.Handler().ServeHTTP(rw, r)
                        return
                }
                v2.Handler().ServeHTTP(rw, r)
                return
        })
        http.ListenAndServe(fmt.Sprintf(":5050"), handler)
}
```

The prefered solution would be, to register both API versions directly at the mux.... @wwwdata got any ideas on how to solve this?

Using this snippet:
```
        v1 := api2go.NewAPI("v1")
        v2 := api2go.NewAPI("v2")
        userStorage := storage.NewUserStorage()
        chocStorage := storage.NewChocolateStorage()
        v1.AddResource(model.User{}, resource.UserResource{ChocStorage: chocStorage, UserStorage: userStorage})
        v2.AddResource(model.User{}, resource.UserResource{ChocStorage: chocStorage, UserStorage: userStorage})
        handler := http.DefaultServeMux
        handler.Handle("/", v1.Handler())
        handler.Handle("/", v2.Handler())
        http.ListenAndServe(fmt.Sprintf(":5050"), handler)
```

will of course yield:
```panic: http: multiple registrations for /```

**Comment by wwwdata** [comment]
yes @sharpner currently you have to do the routing manually if you branch off different versions.

**Comment by sharpner** [comment]
if we would remove the prefix stuff entirely, it would be much more easy to handle e.g.:
```
handler.Handle("/v1", v1.Handler())
handler.Handle("/v2", v2.Handler())
``` 
what do you think?

**Comment by imhuytq** [comment]
@sharpner I think it will return: 404 page not found

**Comment by sharpner** [comment]
sorry to fill up that issue with the discussion :). The first code snippet will work.

**Comment by imhuytq** [comment]
@sharpner Yes. I think it's the only solution right now. Thank you

**Comment by wwwdata** [comment]
The version prefix is optional anyway.  But I think it would be handy to add this into api2go so that it’s possible to create multiple versions without the external mutex. So you can directly register multiple versions with different prefixes.

**Comment by sharpner** [comment]
well not 100% optional, something like this:
```
        v1 := api2go.NewAPI("")
        v2 := api2go.NewAPI("")
        handler := http.DefaultServeMux
        handler.Handle("/v1", v1.Handler())
        handler.Handle("/v2", v2.Handler())
``` 
won't work as expected.. only one api now responds.

**Comment by wwwdata** [comment]
of course, because internally the api2go routing parses the whole url. So you have to give it the full path with a prefix. What I meant is that it's optional in terms of if you don't use it, it doesn't force you to use this url prefix.

So if we make this better and register resources to different prefixes we need a way to do that. So maybe providing a different `addResource` method that takes in the prefix as a parameter for example.

**Comment by wwwdata** [comment]
Ok I looked into this now as well and actually we already have a quite easy way to do this. Which is a bit tricky because of naming and abusing of a feature that was intended for something else, but I will add convenience methods to chain together different versions of api2go apis. So basically you can use the 

https://github.com/manyminds/api2go/blob/8bf46b995b9b98bd0140341534e0ff101f890279/api_public.go#L95-L97

already to register the "v2" or next version number of the api and pass in the `Routeable` from the first api. Which means you pass in the httprouter/other adapters instance of the router to the generator of the next api and therefore register more url to it. With that solution there is no need to have a mux in front of it and all the jsonapi urls are handled by a single router instance.

```go
api := api2go.NewAPI("v0")
api2 := api2go.NewAPIWithRouting("v1", &yourResolver, api.Router())
http.ListenAndServe(fmt.Sprintf(":%d", port), api.Handler())
```
