### ISSUE TITLE
Accessing gin Context from api2go resource handler

### ISSUE THREAD

**Issue by dataBaseError** [manyminds/api2go#317]
Hello,

Is there anyway to copy the context from a routing framework? Specifically the gin framework has [Context](https://godoc.org/github.com/gin-gonic/gin#Context) which you can [get](https://godoc.org/github.com/gin-gonic/gin#Context.Get) or [set](https://godoc.org/github.com/gin-gonic/gin#Context.Set) Keys. While api2go supports [Context](https://godoc.org/github.com/manyminds/api2go#APIContext), context set in Gin does not transfer to api2go.

Is there existing way to support the context store in gin to be transferred to the api2go's context?

An example of this would be using gin middleware login which sets a Key `userID` on login. 

main.go
```go
// ...
r := gin.Default()
api := api2go.NewAPIWithRouting(
  "api",
  api2go.NewStaticResolver("/"),
  routing.Gin(r),
)

// If login is successful will set `userID`.
r.Use(login_handler.AuthMiddleware.MiddlewareFunc())

r.Get("/test", func(c *gin.Context) {
	userId, ok := c.Get("userID")
	// Value will be present
	fmt.Println("User ", userId, " ok ", ok)
}

// ...
api.AddResource(model.User{}, userResource)
// ...
```

user_resource.go
```go
func (s *UserResource) FindAll(r api2go.Request) (api2go.Responder, error) {
	v, ok := r.Context.Get("userID")
	// Value will not be present
	fmt.Println("Account ID ", v, " ok ", ok)

	// ...
}
```

**Comment by sharpner** [comment]
Hello! Unfortunately there is no builtin method. But since our context is an implementation of an interface, in theory it should be possible to write a wrapper for the gin context which implements this interface: https://github.com/manyminds/api2go/blob/master/context.go#L12
and replace the context with https://github.com/manyminds/api2go/blob/master/api_public.go#L37

I hope it helps, and if it does, maybe you can let us know how it turned out :)
